// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6u85SBKjC19iKSm3P_qM8TJsd1YDfnI',
    appId: '1:1084722888039:web:48b57f577770661fd083c2',
    messagingSenderId: '1084722888039',
    projectId: 'chatapp-2c5c5',
    authDomain: 'chatapp-2c5c5.firebaseapp.com',
    databaseURL: 'https://chatapp-2c5c5-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-2c5c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4S-rRccwpODssW6K3nq6qHAbaiRPpWm4',
    appId: '1:1084722888039:android:c776625d460aa49dd083c2',
    messagingSenderId: '1084722888039',
    projectId: 'chatapp-2c5c5',
    databaseURL: 'https://chatapp-2c5c5-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-2c5c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGfX6kI1rp3pkpyXWjmls4BpgvWEBvqgc',
    appId: '1:1084722888039:ios:e3bf070dcc11a7b9d083c2',
    messagingSenderId: '1084722888039',
    projectId: 'chatapp-2c5c5',
    databaseURL: 'https://chatapp-2c5c5-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-2c5c5.appspot.com',
    iosBundleId: 'com.example.teto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGfX6kI1rp3pkpyXWjmls4BpgvWEBvqgc',
    appId: '1:1084722888039:ios:e3bf070dcc11a7b9d083c2',
    messagingSenderId: '1084722888039',
    projectId: 'chatapp-2c5c5',
    databaseURL: 'https://chatapp-2c5c5-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-2c5c5.appspot.com',
    iosBundleId: 'com.example.teto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt6u85SBKjC19iKSm3P_qM8TJsd1YDfnI',
    appId: '1:1084722888039:web:14332d5c2d2b0cf2d083c2',
    messagingSenderId: '1084722888039',
    projectId: 'chatapp-2c5c5',
    authDomain: 'chatapp-2c5c5.firebaseapp.com',
    databaseURL: 'https://chatapp-2c5c5-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-2c5c5.appspot.com',
  );
}
